name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base[version='>=4.2']
  - r-devtools
  - python=3.7
  - pip>=22.3
  - pip:
      - anndata==0.8.0
      - datasets==2.3.2
      - leidenalg==0.8.10
      - llvmlite==0.38.1
      - networkx==2.6.3
      - numba==0.55.2
      - numpy==1.21.6
      - pandas==1.3.5
      - scanpy==1.9.1
      - scikit-learn==1.0.2
      - scikit-misc==0.1.4
      - scipy==1.7.3
      - scvi-tools==0.16.4
      - setuptools==59.5.0
      - scib==1.0.3
      - torch==1.13.0
      - torchtext==0.14.0
      - tqdm==4.64.0
      - transformers==4.20.1
      - typing-extensions==4.2.0
      - umap-learn==0.5.3
      - sphinx<7.0
      - ipykernel
      - nbsphinx
      - git+https://github.com/vidartf/nbsphinx-link.git
      - myst_nb
